### ISSUE TITLE
Broken tests following merge of #69

### ISSUE THREAD

**Issue by cwjohnston** [hw-cookbooks/chef-server-populator#74]
I broke the build by merging #69. I selfishly wanted to see Nellie run the tests. Unfortunately I think the build failed before it could report that the following unit tests are broken:

```
Failures:                                                                                                                                                                                                   [34/1797]

  1) chef-server-populator::client a user is defined in the data bag the user is enabled creates the user
     Failure/Error:
       expect(chef_run).to run_execute("create user: #{test_user_name}").with(
         :command => "chef-server-ctl user-create #{test_user_name} #{test_user_item['chef_server']['full_name'].split(' ').first} #{test_user_item['chef_server']['full_name'].split(' ').last} #{test_user_item['c$
ef_server']['email']} #{test_user_item['chef_server']['password']} > /dev/null 2>&1"
       )

       expected "execute[create user: murph]" with action :run to be in Chef run. Other execute resources:

         execute[create org: endeavor]
         execute[add org validator key: endeavor]
         execute[remove org default validator key: endeavor]
         execute[create org: nasa]
         execute[add org validator key: nasa]
         execute[remove org default validator key: nasa]
         execute[create client: case]
         execute[set client key: case]
         execute[delete default client key: case]
         execute[create client: tars]
         execute[set client key: tars]
         execute[delete default client key: tars]

     # ./test/unit/client_spec.rb:122:in `block (4 levels) in <top (required)>'

  2) chef-server-populator::client a user is defined in the data bag the user is enabled the user has a client key specified creates the user's client key file
     Failure/Error:
       expect(chef_run).to create_file(test_user_pub_key_path).with(
         :content => test_user_item['chef_server']['client_key']
       )

       expected "file[/var/folders/y4/ccjrk8mn4c74ynp2lc7kpnm80000gn/T/d20160511-49588-p3cehy/murph.pub]" with action :create to be in Chef run. Other file resources:

         file[/var/folders/y4/ccjrk8mn4c74ynp2lc7kpnm80000gn/T/d20160511-49588-p3cehy/chef-server-core.firstrun]
         file[/var/folders/y4/ccjrk8mn4c74ynp2lc7kpnm80000gn/T/d20160511-49588-p3cehy/endeavor.pub]
         file[/var/folders/y4/ccjrk8mn4c74ynp2lc7kpnm80000gn/T/d20160511-49588-p3cehy/nasa.pub]
         file[/var/folders/y4/ccjrk8mn4c74ynp2lc7kpnm80000gn/T/d20160511-49588-p3cehy/case.pub]
         file[/var/folders/y4/ccjrk8mn4c74ynp2lc7kpnm80000gn/T/d20160511-49588-p3cehy/tars.pub]

     # ./test/unit/client_spec.rb:130:in `block (5 levels) in <top (required)>'

  3) chef-server-populator::client a user is defined in the data bag the user is enabled the user has a client key specified sets inserts the client key as the user's populator key
     Failure/Error:
       expect(chef_run).to run_execute("set user key: #{test_user_name}").with(
         :command => "chef-server-ctl add-user-key #{test_user_name} --public-key-path #{test_user_pub_key_path} --key-name populator"
       )

       expected "execute[set user key: murph]" with action :run to be in Chef run. Other execute resources:

         execute[create org: endeavor]
         execute[add org validator key: endeavor]
         execute[remove org default validator key: endeavor]
         execute[create org: nasa]
         execute[add org validator key: nasa]
         execute[remove org default validator key: nasa]
         execute[create client: case]
         execute[set client key: case]
         execute[delete default client key: case]
         execute[create client: tars]
         execute[set client key: tars]
         execute[delete default client key: tars]

  4) chef-server-populator::client a user is defined in the data bag the user is enabled the user has a client key specified deletes the user's default key
     Failure/Error: expect(chef_run).to run_execute("delete default user key: #{test_user_name}")

       expected "execute[delete default user key: murph]" with action :run to be in Chef run. Other execute resources:

         execute[create org: endeavor]
         execute[add org validator key: endeavor]
         execute[remove org default validator key: endeavor]
         execute[create org: nasa]
         execute[add org validator key: nasa]
         execute[remove org default validator key: nasa]
         execute[create client: case]
         execute[set client key: case]
         execute[delete default client key: case]
         execute[create client: tars]
         execute[set client key: tars]
         execute[delete default client key: tars]

     # ./test/unit/client_spec.rb:142:in `block (5 levels) in <top (required)>'

Finished in 59.01 seconds (files took 1.82 seconds to load)
62 examples, 4 failures

Failed examples:

rspec ./test/unit/client_spec.rb:121 # chef-server-populator::client a user is defined in the data bag the user is enabled creates the user
rspec ./test/unit/client_spec.rb:129 # chef-server-populator::client a user is defined in the data bag the user is enabled the user has a client key specified creates the user's client key file
rspec ./test/unit/client_spec.rb:135 # chef-server-populator::client a user is defined in the data bag the user is enabled the user has a client key specified sets inserts the client key as the user's populator key
rspec ./test/unit/client_spec.rb:141 # chef-server-populator::client a user is defined in the data bag the user is enabled the user has a client key specified deletes the user's default key

``` 

Are the tests or fixtures in need of updating with this change?

**Comment by cwjohnston** [comment]
cc @luckymike

**Comment by luckymike** [comment]
:/

**Comment by luckymike** [comment]
I guess so? I thought I ran them before, but `require_relative` in LWRPs is broken outside of ChefDK for me, so I wasn't on my usual development system. Maybe missed this PR, or maybe something went sideways with the collection of PRs coming together.
